// Code generated by github.com/gregfurman/genver DO NOT EDIT.
package genver

// Currently using golang.org/x/crypto v0.21.0 
const (
    XCrypto_Golang_Version = "v0.21.0"
    XCrypto_Golang_Path    = "golang.org/x/crypto"
)

// Currently using golang.org/x/mod v0.8.0 
const (
    XMod_Golang_Version = "v0.8.0"
    XMod_Golang_Path    = "golang.org/x/mod"
)

// Currently using golang.org/x/net v0.22.0 
const (
    XNet_Golang_Version = "v0.22.0"
    XNet_Golang_Path    = "golang.org/x/net"
)

// Currently using golang.org/x/sys v0.18.0 
const (
    XSys_Golang_Version = "v0.18.0"
    XSys_Golang_Path    = "golang.org/x/sys"
)

// Currently using golang.org/x/term v0.18.0 
const (
    XTerm_Golang_Version = "v0.18.0"
    XTerm_Golang_Path    = "golang.org/x/term"
)

// Currently using golang.org/x/text v0.14.0 
const (
    XText_Golang_Version = "v0.14.0"
    XText_Golang_Path    = "golang.org/x/text"
)

// Currently using golang.org/x/tools v0.6.0 
const (
    XTools_Golang_Version = "v0.6.0"
    XTools_Golang_Path    = "golang.org/x/tools"
)
