// Code generated by github.com/gregfurman/genver DO NOT EDIT.
package main

// Currently using github.com/davecgh/go-spew v1.1.1 
const (
    DavecghGoSpew_Github_Version = "v1.1.1"
    DavecghGoSpew_Github_Path    = "github.com/davecgh/go-spew"
)

// Currently using github.com/pmezard/go-difflib v1.0.0 
const (
    PmezardGoDifflib_Github_Version = "v1.0.0"
    PmezardGoDifflib_Github_Path    = "github.com/pmezard/go-difflib"
)

// Currently using github.com/sirupsen/logrus v1.9.3 
const (
    SirupsenLogrus_Github_Version = "v1.9.3"
    SirupsenLogrus_Github_Path    = "github.com/sirupsen/logrus"
)

// Currently using github.com/stretchr/objx v0.1.0 
const (
    StretchrObjx_Github_Version = "v0.1.0"
    StretchrObjx_Github_Path    = "github.com/stretchr/objx"
)

// Currently using github.com/stretchr/testify v1.7.0 
const (
    StretchrTestify_Github_Version = "v1.7.0"
    StretchrTestify_Github_Path    = "github.com/stretchr/testify"
)

// Currently using golang.org/x/sys v0.0.0-20220715151400-c0bba94af5f8 
const (
    XSys_Golang_Version = "v0.0.0-20220715151400-c0bba94af5f8"
    XSys_Golang_Path    = "golang.org/x/sys"
)

// Currently using gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 
const (
    CheckV1_Gopkg_Version = "v0.0.0-20161208181325-20d25e280405"
    CheckV1_Gopkg_Path    = "gopkg.in/check.v1"
)

// Currently using gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c 
const (
    YamlV3_Gopkg_Version = "v3.0.0-20200313102051-9f266ea9e77c"
    YamlV3_Gopkg_Path    = "gopkg.in/yaml.v3"
)
